feat(openresty) bundle Kong/lua-resty-websocket
This adds Kong's fork of lua-resty-websocket to kong-ngx-build. This
is opt-in for now but expected to be standard later on.

diff --git a/openresty-build-tools/kong-ngx-build b/openresty-build-tools/kong-ngx-build
--- a/openresty-build-tools/kong-ngx-build
+++ b/openresty-build-tools/kong-ngx-build
@@ -15,6 +15,7 @@ FORCE=0
 OPENRESTY_PATCHES=$OPENRESTY_PATCHES
 KONG_NGINX_MODULE=master
 RESTY_LMDB=master
+RESTY_WEBSOCKET=${RESTY_WEBSOCKET:-0}
 DEBUG=0
 NPROC=
 OS=
@@ -94,6 +95,10 @@ main() {
         ;;
       --no-resty-lmdb)
         RESTY_LMDB=0
+        shift 1
+        ;;
+      --resty-websocket)
+        RESTY_WEBSOCKET=$2
         shift 1
         ;;
       -f|--force)
@@ -280,6 +285,23 @@ main() {
             rm -f lua-resty-dns-0.21.tar.gz
           popd
         fi
+
+        if [[ $RESTY_WEBSOCKET != 0 ]]; then
+          pushd openresty-$OPENRESTY_VER/bundle
+            if ! rm -rf lua-resty-websocket-*; then
+              fatal "Failed to find/remove upstream lua-resty-websocket component"
+            fi
+            mkdir "lua-resty-websocket-${RESTY_WEBSOCKET}"
+            notice "Downloading Kong/lua-resty-websocket $RESTY_WEBSOCKET"
+            curl -sSL \
+              -o lua-resty-websocket.tar.gz \
+              "https://github.com/Kong/lua-resty-websocket/archive/refs/tags/${RESTY_WEBSOCKET}.tar.gz"
+            tar -xzf lua-resty-websocket.tar.gz \
+              -C "lua-resty-websocket-${RESTY_WEBSOCKET}" \
+              --strip-components 1
+            rm -f lua-resty-websocket.tar.gz
+          popd
+        fi
       fi
     fi
 
@@ -388,6 +410,16 @@ main() {
       pushd $OPENRESTY_DOWNLOAD/bundle
         if [ ! -f .patch_applied ]; then
           for patch_file in $(ls -1 $OPENRESTY_PATCHES_DIR/patches/$OPENRESTY_VER/*.patch); do
+            # any existing patch files will surely conflict with our fork of
+            # lua-resty-websocket, so skip them if bundling Kong/lua-resty-websocket
+            if
+              [[ $RESTY_WEBSOCKET != 0 ]] &&
+              [[ "$(basename "$patch_file")" = lua-resty-websocket-* ]]
+            then
+              notice "Skipping lua-resty-websocket patch: $patch_file"
+              continue
+            fi
+
             notice "Applying OpenResty patch $patch_file"
             patch -p1 < $patch_file \
               || fatal "failed to apply patch: $patch_file"
@@ -811,6 +843,9 @@ show_usage() {
   echo ""
   echo "      --resty-lmdb <branch>          Specify a lua-resty-lmdb branch to use when patching and compiling."
   echo "                                     (Defaults to \"master\")"
+  echo ""
+  echo "      --resty-websocket <tag>        Specify a Kong/lua-resty-websocket tag to install in place of the"
+  echo "                                     bundled version of lua-resty-websocket (Defaults to \"$RESTY_WEBSOCKET\")"
   echo ""
   echo "      --luarocks <luarocks_ver>      Version of LuaRocks to build, such as 3.1.2. If absent, LuaRocks"
   echo "                                     will not be built."
